/**
 * @description Models connects to MongoDB and create new DB
 * @requires mongoose, ../dbsupport.js
 */
const mongoose = require("mongoose");
const { getConnString } = require("../../dbsupport");

const db = "forumDB";
mongoose.connect(getConnString(db))
        .then(() => console.log("Connected to MongoDB!"))
        .catch((error) => console.log(`Cannot connect to MongoDB. The error is ${error}`));

/* Define Schemas */
const userSchema = new mongoose.Schema({
    name: { type: String, required: true },
    email: { type: String, required: true, unique: true },
});
const postSchema = new mongoose.Schema({
    title: { type: String, required: true },
    content: { type: String, required: true },
    author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    topic: {type: mongoose.Schema.Types.ObjectId, ref: 'Topic', required: true },
    categories: [{type: mongoose.Schema.Types.ObjectId, ref: 'Category'}],
});
const topicSchema = new mongoose.Schema({
    name: {type: String, required: true, unique: true },
    description: String,
});
const categorySchema = new mongoose.Schema({
    name: {type: String, required: true, unique: true}
}); 

/* Produce models */
const User = mongoose.model("User", userSchema);
const Post = mongoose.model("Post", postSchema);
const Topic = mongoose.model("Topic", topicSchema);
const Category = mongoose.model("Category", categorySchema);

/**
 * It's not recommended to call mongoose.connection.close() here,
 * because this file is meant to define models and establish a connection
 * for use throughout your application. Closing the connection here would
 * prevent other parts of your app from interacting with the database.
 * 
 * Only close the connection when your entire app is shutting down,
 * typically handled in your main entry point or with process event handlers.
 * (Generated by Gihub Copilot 
 */

module.exports = { User, Post, Topic, Category }